version: 2

jobs:
  build:
    working_directory: ~/DjangoBrothers-blog
    docker:
      - image: circleci/python:3.8.3
        environment:
          PYTHONUNBUFFERED: 1
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          TZ: Asia/Tokyo
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: |
            . venv/bin/activate
            echo $ENV_FILE | base64 -di > .env
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py test
